# SPDX-FileCopyrightText: 2026 Alexandru Fikl <alexfikl@gmail.com>
# SPDX-License-Identifier: MIT

from __future__ import annotations

import os
from dataclasses import Field
from typing import Any, ClassVar, Protocol, TypeAlias

import numpy as np
from typing_extensions import TypeAliasType, TypeVar

T = TypeVar("T")
"""An unbound invariant generic type variable."""

PathLike: TypeAlias = os.PathLike[str] | str
"""A union of types supported as paths."""

# FIXME: maybe https://github.com/data-apis/array-api-typing will work some day.
# Now, it seems pretty empty, so not sure it's worth doing more than this..

ShapeT_co = TypeVar(
    "ShapeT_co", bound=tuple[int, ...], default=tuple[Any, ...], covariant=True
)
"""A covariant type variable for array shapes (``tuple[int, ...]``)."""
DTypeT = TypeVar("DTypeT", bound=np.dtype[Any], default=Any)
"""An invariant type alias for ``np.dtype``."""
ScalarTypeT = TypeVar("ScalarTypeT", bound=np.generic, default=Any)
"""An invariant type alias for :mod:`numpy` scalars."""


class Array(Protocol[ShapeT_co, DTypeT]):  # noqa: PLR0904
    """A minimal protocol compatible with the
    `Array API <https://data-apis.org/array-api/latest/API_specification/array_object.html>`__.
    """

    @property
    def dtype(self) -> Any: ...
    @property
    def device(self) -> Any: ...
    @property
    def ndim(self) -> int: ...
    # NOTE: torch.Tensor returns torch.Sized here, not tuple[int, ...]
    @property
    def shape(self) -> Any: ...

    # NOTE: torch.Tensor defines this as a method instead
    # @property
    # def size(self) -> int: ...

    # Arithmetic operators
    def __pos__(self) -> Any: ...
    def __neg__(self) -> Any: ...
    def __add__(self, other: Any, /) -> Any: ...
    def __sub__(self, other: Any, /) -> Any: ...
    def __mul__(self, other: Any, /) -> Any: ...
    def __truediv__(self, other: Any, /) -> Any: ...
    def __floordiv__(self, other: Any, /) -> Any: ...
    def __mod__(self, other: Any, /) -> Any: ...
    def __pow__(self, other: Any, /) -> Any: ...

    # Array operators
    def __matmul__(self, other: Any, /) -> Any: ...

    # Bitwise operators
    def __invert__(self) -> Any: ...
    def __and__(self, other: Any, /) -> Any: ...
    def __or__(self, other: Any, /) -> Any: ...
    def __xor__(self, other: Any, /) -> Any: ...
    def __lshift__(self, other: Any, /) -> Any: ...
    def __rshift__(self, other: Any, /) -> Any: ...

    # Comparison operators
    # def __lt__(self, other: Any, /) -> Any: ...
    # def __le__(self, other: Any, /) -> Any: ...
    # def __gt__(self, other: Any, /) -> Any: ...
    # def __ge__(self, other: Any, /) -> Any: ...
    # def __eq__(self, other: Any, /) -> Any: ...
    # def __ne__(self, other: Any, /) -> Any: ...

    # In-place operators
    # def __iadd__(self, other: Any, /) -> Any: ...
    # def __isub__(self, other: Any, /) -> Any: ...
    # def __imul__(self, other: Any, /) -> Any: ...
    # def __itruediv__(self, other: Any, /) -> Any: ...
    # def __ifloordiv__(self, other: Any, /) -> Any: ...
    # def __ipow__(self, other: Any, /) -> Any: ...
    # def __imod__(self, other: Any, /) -> Any: ...
    # def __imatmul__(self, other: Any, /) -> Any: ...
    # def __iand__(self, other: Any, /) -> Any: ...
    # def __ior__(self, other: Any, /) -> Any: ...
    # def __ixor__(self, other: Any, /) -> Any: ...
    # def __ilshift__(self, other: Any, /) -> Any: ...
    # def __irshift__(self, other: Any, /) -> Any: ...

    # Reflected operators
    def __radd__(self, other: Any, /) -> Any: ...
    def __rsub__(self, other: Any, /) -> Any: ...
    def __rmul__(self, other: Any, /) -> Any: ...
    def __rtruediv__(self, other: Any, /) -> Any: ...
    def __rfloordiv__(self, other: Any, /) -> Any: ...
    def __rpow__(self, other: Any, /) -> Any: ...
    def __rmod__(self, other: Any, /) -> Any: ...
    def __rmatmul__(self, other: Any, /) -> Any: ...
    def __rand__(self, other: Any, /) -> Any: ...
    def __ror__(self, other: Any, /) -> Any: ...
    def __rxor__(self, other: Any, /) -> Any: ...
    def __rlshift__(self, other: Any, /) -> Any: ...
    def __rrshift__(self, other: Any, /) -> Any: ...

    # Methods
    def __abs__(self) -> Any: ...
    # NOTE: torch.Tensor does not define __array_namespace__
    # def __array_namespace__(self, *, api_version: Any = None) -> Any: ...
    # def __bool__(self) -> bool: ...
    # def __complex__(self) -> complex: ...
    # def __dlpack__(self, *, stream=None, copy=None) -> Any: ...
    # def __dlpack_device__(self) -> tuple[int, int]: ...
    # def __float__(self) -> float: ...
    def __getitem__(self, key: Any, /) -> Any: ...
    # def __index__(self) -> int: ...
    # def __int__(self) -> int: ...
    # def to_device(self, device: Any, /, stream: Any = None) -> None: ...
    def __setitem__(self, key: Any, value: Any, /) -> None: ...

    # Not part of the Array API
    def __len__(self) -> int: ...
    def __iter__(self) -> Any: ...


Array0D = TypeAliasType(
    "Array0D",
    Array[tuple[()], np.dtype[ScalarTypeT]],
    type_params=(ScalarTypeT,),
)
"""A type alias for a 0-dimensional array."""
Array1D = TypeAliasType(
    "Array1D",
    Array[tuple[int], np.dtype[ScalarTypeT]],
    type_params=(ScalarTypeT,),
)
"""A type alias for a 1-dimensional array."""
Array2D = TypeAliasType(
    "Array2D",
    Array[tuple[int, int], np.dtype[ScalarTypeT]],
    type_params=(ScalarTypeT,),
)
"""A type alias for a 2-dimensional array."""
Array3D = TypeAliasType(
    "Array3D",
    Array[tuple[int, int, int], np.dtype[ScalarTypeT]],
    type_params=(ScalarTypeT,),
)
"""A type alias for a 3-dimensional array."""
Array4D = TypeAliasType(
    "Array4D",
    Array[tuple[int, int, int, int], np.dtype[ScalarTypeT]],
    type_params=(ScalarTypeT,),
)
"""A type alias for a 4-dimensional array."""
ArrayND = TypeAliasType(
    "ArrayND",
    Array[tuple[int, ...], np.dtype[ScalarTypeT]],
    type_params=(ScalarTypeT,),
)
"""A type alias for an n-dimensional array."""

DTypeLike: TypeAlias = Any
"""A :class:`numpy.dtype` like object."""


class DataclassInstance(Protocol):
    """Dataclass protocol from
    `typeshed <https://github.com/python/typeshed/blob/770724013de34af6f75fa444cdbb76d187b41875/stdlib/_typeshed/__init__.pyi#L329-L334>`__."""

    __dataclass_fields__: ClassVar[dict[str, Field[Any]]]


DataclassInstanceT = TypeVar("DataclassInstanceT", bound=DataclassInstance)
"""An invariant :class:`~typing.TypeVar` bound to :class:`DataclassInstance`."""
